name: Run tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3

      - name: Install dependecies
        run: npm install

      - name: Run tests
        run: npm run test -- --coverage

  check-coverage:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check test coverage
        run: |
          if [ ! -f ./coverage/coverage-final.json ]; then
          echo "Coverage report not found!"
          exit 1
          fi

          echo "Coverage report found"

          COVERAGE=$(cat ./coverage/coverage-final.json | jq .total.lines.pct)
          echo "Test coverage is ${COVERAGE}%"

          if (( $(echo "$COVERAGE < 90" | bc -l) )); then
          echo "Test coverage is below 90%, cannot deploy."
          exit 1
          fi
