name: Run tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3

      - name: Install dependecies
        run: npm install

      - name: Run tests
        run: npm run test -- --coverage

  check-coverage:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check test coverage
        run: |
          if [ ! -f ./coverage/coverage-final.json ]; then
            echo "Coverage report not found!"
            exit 1
          fi

          COVERAGE=$(jq '.[].s | select(. != null) | .[]' ./coverage/coverage-final.json)

          TOTAL=0
          COUNT=0

          for value in $COVERAGE; do
            TOTAL=$(echo "$TOTAL + $value" | bc)
            COUNT=$((COUNT + 1))
          done

          if [ $COUNT -eq 0 ]; then
            echo "No coverage data found!"
            exit 1
          fi

          AVERAGE=$(echo "scale=2; $TOTAL / $COUNT" | bc)
          echo "Average lines coverage is ${AVERAGE}%"

          if (( $(echo "$AVERAGE < 90" | bc -l) )); then
            echo "Test coverage is below 90%, cannot deploy."
            exit 1
          fi

          echo "Test coverage is sufficient."
  deploy:
    runs-on: ubuntu-latest
    needs: check-coverage

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
